#!/bin/bash
# Author: Andrew Kassab
# Description: Handles bash tab-completion for the precisepass 
#              password manager.
# Date: 03-01-2019

OPTS="--add --get --edit --remove --help"

if [ -d ~/.precisepass ]; then
    PLATFORMS=`cat ~/.precisepass/platforms.txt` 
else 
    PLATFORMS=''
fi

# handles completions 
pass_completions(){
    
    cur=${COMP_WORDS[COMP_CWORD]}
    prev=${COMP_WORDS[COMP_CWORD-1]}

    # if we are on the 1st argument
    if [ $COMP_CWORD -eq 1 ]; then
        COMPREPLY=($(compgen -W "${OPTS}" -- $cur) ) 
    elif [ $COMP_CWORD -eq 2 ]; then
        case "$prev" in
            "-g")
                COMPREPLY=($(compgen -W "${PLATFORMS}" -- $cur))
                ;;
            "-e")
                COMPREPLY=($(compgen -W "${PLATFORMS}" -- $cur))
                ;;
            "-r")
                COMPREPLY=($(compgen -W "${PLATFORMS}" -- $cur))
                ;;
            "--get")
                COMPREPLY=($(compgen -W "${PLATFORMS}" -- $cur))
                ;;
            "--edit")
                COMPREPLY=($(compgen -W "${PLATFORMS}" -- $cur))
                ;;
            "--remove")
                COMPREPLY=($(compgen -W "${PLATFORMS}" -- $cur))
                ;;
            *)
                return
                ;;
        esac
    fi
}

complete -F pass_completions pass
