#!/bin/bash
# Author: Andrew Kassab
# Description: Handles bash tab-completion for the precisepass 
#              password manager.
# Date: 03-01-2019

OPTS="--add --get --edit --remove --help"
PLATFORMS=`cat /etc/platforms.txt` 

# handles completions 
opt_completions(){
    
    cur=${COMP_WORDS[COMP_CWORD]}
    prev=${COMP_WORDS[COMP_CWORD-1]}

    # if we are on the 1st argument
    if [ $COMP_CWORD -eq 1 ]; then
        COMPREPLY=($(compgen -W "${OPTS}" -- $cur) ) 
    elif [ $COMP_CWORD -eq 2 ]; then
        case "$prev" in
            "--add")
                return
                ;;
            "--help")
                return 
                ;;
            *)
                COMPREPLY=($(compgen -W "${PLATFORMS}" -- $cur))
                ;;
        esac
    fi
}

complete -F opt_completions pass
